### ISSUE TITLE
N_VRAD for VAD

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#6]
The VAD of Payerne has 12 beams and is done every 30 min. I use averaging of 60 min, so two scans. To get any output, I need to set N_VRAD to 4. This seems very low. I would expect, that a value of 8 beams should be ok. Can you check, what is going on there?

**Comment by jana-p** [comment]
Same happens with the new data set from Feb 9th. How is N_VRAD used for VAD?

**Comment by mkay-atm** [comment]
N_VRAD is the minimal number of available line-of-sight directions that are used the retrieval. As an example, if you measure with a VAD with 12 fixed azimuth direction, dividing the circle into 30 degree steps, you need at least 3 directions to perform the retrieval. But the results are much more reliable, if you choose a bigger number, like 6, i.e. half of the maximal number of available directions. Before the retrieval is performed, the data is filtered for each of the fixed directions, but taking into accout the all the radial velocities matching theses directions. If I set the averaging time to 30 min and the instruments did 10 whole sweeps in this time window, the algorithm will choose the most likely radial velocities for each direction among 10 measurements. If some directions end-up without a valid radial velocity, the number of available directions is reduced by that amount and if this number turns out to be less than the specified N_VRAD threshold, the output will be NaN.

**Comment by jana-p** [comment]
Thank you for clarifying.
